# Generated by Django 6.0.1 on 2026-02-05 07:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('is_respectful', models.BooleanField(default=False, verbose_name='Поважна причина')),
            ],
            options={
                'verbose_name': 'Причина пропуску',
                'verbose_name_plural': 'Причини пропусків',
                'db_table': 'absence_reasons',
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назва/Номер')),
                ('building', models.CharField(blank=True, max_length=100, verbose_name='Корпус')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Місткість')),
            ],
            options={
                'verbose_name': 'Аудиторія',
                'verbose_name_plural': 'Аудиторії',
                'db_table': 'classrooms',
            },
        ),
        migrations.CreateModel(
            name='EvaluationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип заняття (Лекція/Практика)')),
                ('weight_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Вплив на оцінку (%)')),
            ],
            options={
                'verbose_name': 'Тип оцінювання',
                'verbose_name_plural': 'Типи оцінювання',
                'db_table': 'evaluation_types',
            },
        ),
        migrations.CreateModel(
            name='GradingScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назва шкали')),
            ],
            options={
                'verbose_name': 'Шкала оцінювання',
                'verbose_name_plural': 'Шкали оцінювання',
                'db_table': 'grading_scales',
            },
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назва групи')),
            ],
            options={
                'verbose_name': 'Група',
                'verbose_name_plural': 'Групи',
                'db_table': 'study_groups',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва предмету')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предмети',
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.PositiveSmallIntegerField(unique=True, verbose_name='Номер пари')),
                ('start_time', models.TimeField(verbose_name='Початок')),
                ('end_time', models.TimeField(verbose_name='Кінець')),
            ],
            options={
                'verbose_name': 'Розклад дзвінків',
                'verbose_name_plural': 'Розклад дзвінків',
                'db_table': 'time_slots',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('full_name', models.CharField(max_length=255, verbose_name='ПІБ')),
                ('role', models.CharField(choices=[('admin', 'Адміністратор'), ('teacher', 'Викладач'), ('student', 'Студент')], default='student', max_length=10, verbose_name='Роль')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='main.studygroup')),
            ],
            options={
                'verbose_name': 'Користувач',
                'verbose_name_plural': 'Користувачі',
                'db_table': 'tbl_users',
            },
        ),
        migrations.CreateModel(
            name='GradeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='Оцінка (словом/буквою)')),
                ('min_points', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Мінімальний бал')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='main.gradingscale')),
            ],
            options={
                'verbose_name': 'Правило оцінювання',
                'verbose_name_plural': 'Правила оцінювання',
                'db_table': 'grade_rules',
                'ordering': ['-min_points'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Пн'), (2, 'Вт'), (3, 'Ср'), (4, 'Чт'), (5, 'Пт'), (6, 'Сб'), (7, 'Нд')], verbose_name='День тижня')),
                ('lesson_number', models.PositiveSmallIntegerField(default=1, verbose_name='Номер пари')),
                ('start_time', models.TimeField(verbose_name='Час початку')),
                ('duration_minutes', models.IntegerField(default=80, verbose_name='Тривалість (хв)')),
                ('valid_from', models.DateField(auto_now_add=True, verbose_name='Діє з')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Діє до')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.classroom', verbose_name='Аудиторія')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Викладач')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.studygroup', verbose_name='Група')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Шаблон розкладу',
                'verbose_name_plural': 'Шаблони розкладу',
                'db_table': 'schedule_templates',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Час початку')),
                ('end_time', models.TimeField(verbose_name='Час закінчення')),
                ('topic', models.CharField(blank=True, max_length=255, verbose_name='Тема заняття')),
                ('max_points', models.PositiveIntegerField(default=5, verbose_name='Макс. балів')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.classroom', verbose_name='Аудиторія')),
                ('evaluation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.evaluationtype', verbose_name='Тип заняття')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Викладач')),
                ('template_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.scheduletemplate', verbose_name='Джерело (шаблон)')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.studygroup', verbose_name='Група')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'db_table': 'lessons',
                'ordering': ['-date', 'start_time'],
                'unique_together': {('group', 'date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.studygroup', verbose_name='Група')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Викладач')),
            ],
            options={
                'verbose_name': 'Навантаження викладача',
                'verbose_name_plural': 'Навантаження викладачів',
                'db_table': 'teaching_assignments',
                'unique_together': {('subject', 'teacher', 'group')},
            },
        ),
        migrations.AddField(
            model_name='scheduletemplate',
            name='teaching_assignment',
            field=models.ForeignKey(blank=True, help_text="Зв'язок з призначенням викладача (subject+teacher+group)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_templates', to='main.teachingassignment', verbose_name='Навантаження викладача'),
        ),
        migrations.AddField(
            model_name='evaluationtype',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_types', to='main.teachingassignment'),
        ),
        migrations.CreateModel(
            name='StudentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_points', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Набрані бали')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Коментар')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('absence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.absencereason', verbose_name='Пропуск')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='main.lesson')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Успішність студента',
                'verbose_name_plural': 'Успішність студентів',
                'db_table': 'student_performance',
                'unique_together': {('lesson', 'student')},
            },
        ),
    ]
