# Generated by Django 6.0.1 on 2026-02-05 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentperformance',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Коментар'),
        ),
        migrations.CreateModel(
            name='BuildingAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Час події')),
                ('action', models.CharField(choices=[('ENTER', 'Вхід'), ('EXIT', 'Вихід')], max_length=10, verbose_name='Дія')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Лог доступу',
                'verbose_name_plural': 'Логи доступу',
                'db_table': 'building_access_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
